version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    restart: always
    env_file: .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    command: >
      sh -c "
        until pg_isready -h db -p 5432; do echo 'Waiting for Postgres...'; sleep 1; done &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn nsk.wsgi:application --bind 0.0.0.0:8000
      "
    networks:
      - backend

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: always 
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - media_volume:/media
      - ./frontend/build:/usr/share/nginx/html
    networks:
      - backend

volumes:
  static_volume:
  media_volume:
  postgres_data:

networks:
  backend:
