FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# Установка зависимостей
COPY ./requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

# Копируем проект
COPY ./backend /app

# Открываем порт
EXPOSE 8000

# Команда запуска
CMD ["gunicorn", "nsk.wsgi:application", "--bind", "0.0.0.0:8000"]
